### ISSUE TITLE
applesmc not loaded

### ISSUE THREAD

**Issue by trickpattyFH20** [marcosfad/mbp-ubuntu-kernel#11]
I’m running the iso on a mbp 16.1 with the T2 chip.

I don’t see the applesmc module loaded in `lsmod` 

However if I run `modinfo applesmc` I see this output:

name: applesmc
filename: (builtin)
license: GPL v2
file: drivers/hwmon/applesmc
description: Apple SMC
author: Paul Pawlowski
author: Nicolas Boichat

I added applesmc to /etc/modules-load/modules.conf but the module still won’t load.

My overall goal is to find a way to use mbpfan to boost my fans to maximum rpm to keep my mbp from getting too hot, which requires applesmc to be installed. Is there a way to do that with the applesmc driver that is already built into the iso?

**Comment by Redecorating** [comment]
As the applesmc module is builtin, it doesn't need loading (if you are looking for the sysfs entries, they should be at `/sys/bus/acpi/devices/APP0001:00` with t2 versions of applesmc). You might want to use the fan control daemon described [here](https://wiki.t2linux.org/guides/fan/), you can force a speed by editing `/etc/mbpfan.conf`.
