### ISSUE TITLE
Trackpad scrolling not working after ubuntu update on MacBook Pro 16,1

### ISSUE THREAD

**Issue by AdityaGarg8** [marcosfad/mbp-ubuntu-kernel#15]
After updating to ubuntu 20.10 Groovy, trackpad scrolling and right click has stopped working. Trackpad is being treated as a mouse.

**Comment by Redecorating** [comment]
What's the output of `uname -r`?

**Comment by AdityaGarg8** [comment]
> What's the output of `uname -r`?

5.8.5-59 generic

**Comment by networkException** [comment]
5.8 and 5.9 are not considered stable, either wait for this repository to update to a newer version, folllow the guide to patch and compile a more recent kernel yourself on [wiki.t2linux.org](https://wiki.t2linux.org/guides/kernel) or look at [this fork](https://github.com/Redecorating/mbp-ubuntu-kernel) of mbp-ubuntu-kernel with more recent versions.
