### ISSUE TITLE
Is there any ISO-ready version to try?

### ISSUE THREAD

**Issue by chenming-wu** [marcosfad/mbp-ubuntu-kernel#3]
Thanks for sharing this repo!

**Comment by marcosfad** [comment]
Hi, glad you have interest. I've finish compiling an ISO on the weekend. You can check it out from https://github.com/marcosfad/mbp-ubuntu/releases (as soon as Travis finish building it).
I'm using a map 16,1 that is the only laptop I've tested.
I look forward for your feedback. Feel free to create any pull request you see necessary.
My goal was to be able to install a minimal ubuntu desktop without using an external Keyboard or Mouse.

**Comment by drst3in** [comment]
First of all, thank you for your hard work.
We apologize for the poor English.
I am a Korean and I tried to install Ubuntu by purchasing a 16-inch MacBook.
So if you give it the iso you gave it, it will stop on boot.
So after installing Ubuntu 20.04, use your keyboard, t2, trackpad patch
The patch has been completed.
But wifi is not installed.

     | | | | | "RequestedFiles" = ({"Firmware" = "C-4364__s-B3 / bali.trx", "TxCap" = "C-4364__s-B3 / bali-X3.txcb", "Regulatory" = "C-4364__s-B3 /bali-X3.clmb","NVRAM"="C-4364__s-B3/P-bali-X3_M-HRPN_V-m__m-7.9.txt "})

This is the wifi information of my MacBook. It comes out as a bali, but wifi does not work even if you try everything.
Do you know anything about this?

**Comment by kazazes** [comment]
@marcosfad gonna give that ISO a shot now, also on 16,1.
