### ISSUE TITLE
Testing on a 16,2

### ISSUE THREAD

**Issue by zappacor** [marcosfad/mbp-ubuntu-kernel#6]
Hi guys, tested both 5.8.5-mbp-alt and 5.8.5-mbp on a 16,2.
The keyboard (only thing I'm interested in, at least for now) doesn't work.
Willing to help so lemme know if there is anything I can do or try.

**Comment by Redecorating** [comment]
It might be worth trying the [5.7.19 version](https://github.com/marcosfad/mbp-ubuntu-kernel/releases/tag/v5.7.19), as many people have had problems with the 5.8 kernel.

**Comment by marcosfad** [comment]
Yes, Redecorating is right. Can you please test with a 5.7 version and post your results? I would also recommend you to join the discord channel. There you will find also a lot of helpful people.

**Comment by zappacor** [comment]
Tried with 5.7.19 today and same results, unfortunatelly.
Will check the channel you mentioned.
Meanwhile, thanks Marcos for your great job!

**Comment by zappacor** [comment]
As an update, could spend a few cycles last night and realized I hadn't installed `dkms `, my bad!

So, for me, 5.8.13 works the best: with 5.7.19 it's like the terminal has more lines that the ones that are actually displayed on the screen (I don't care about any graphical interface, sound, etc so didn't test them).

A few comments/questions:
1. regardless of using the `mbp `or the `mbp-alt` variant, I could see the drivers being added when issuing `update-initramfs`. So, I'm a bit confused of what drivers are included and not included on each one...
2. I still have to connect a USB keyboard to login and manually `modprobe apple-bce`, have to dig into that too.
3. the touchbar got activated but didn't display the Fx icons, nothing happened when I pressed it and got an error message from its driver complaining it couldn't set fnmode=2. Will google about it in a while and/or open a ticket in the github git where it's been developed.

Anyways, at least... it looks promising, thanks Marcos and all @discord!

**Comment by zappacor** [comment]
Good news: could spend some time earlier today and realized everything works fine!
For the record if it helps others: I was using a really old USB hub to connect the flash drive I boot from as well as the external keyboard from a single port on the MBP.
So, when removing all that and connecting just the flash drive (no hub), everything started to work as expected.
I'm now closing this issue.
