### ISSUE TITLE
packages dependencies

### ISSUE THREAD

**Issue by zappacor** [marcosfad/mbp-ubuntu-kernel#7]
Hey Marcos, what packages do your two kernel packages depend on?

I believe dkms and initramfs-tools are a must but I'm getting some warning messages mentioning apt-utils which sounds like I can ignore them.

So, besides dkms and initram-tools, anything else?

**Comment by networkException** [comment]
I believe that all dependencies are listed in [build.sh](https://github.com/marcosfad/mbp-ubuntu-kernel/blob/master/build.sh) at line 42.

**Comment by marcosfad** [comment]
Hi, I must admit, that I'm not 100% sure, but I would say, that the build package only depends on `linux-base`. The dependency listed on the build.sh are the requirements to build the kernel and those are only needed to build it, not to run it.

`dkms` and `initramfs-tools` would be recommendations, as you don't need them to install or use the kernel. 
`dkms` is used to install extra drivers, that are not present in the kernel packages (apple-bce and apple-ibridge).
`initramfs-tool` is to customise the boot process. 

But I am just guessing.

**Comment by zappacor** [comment]
Ok, so I made I clean, basic install with `debootstrap` and can confirm it was enough to just install `initramfs-tools` and `dkms`.
That said... during the process I recalled I had to then follow these steps for everything to work:
```
sudo apt install dkms
sudo apt install linux-headers-<mbp-kernel-release>-mbp linux-image-<mbp-kernel-release>-mbp
sudo git clone --branch mbp15 https://github.com/roadrunner2/macbook12-spi-driver.git /usr/src/apple-ibridge-0.1
sudo dkms install -m apple-ibridge -v 0.1 -k <mbp-kernel-release>-mbp
modprobe apple-ib-tb
modprobe apple-ib-als
sudo git clone --branch aur https://github.com/marcosfad/mbp2018-bridge-drv.git /usr/src/apple-bce-0.1
sudo dkms install -m apple-bce -v 0.1 -k <mbp-kernel-release>-mbp
modprobe apple-bce
```
So... @marcosfad: shouldn't the modules created by above `dkms install` steps be included in the `5.8.*-mbp` kernels you're releasing yet?

**Comment by marcosfad** [comment]
I've already try. You will find the code commented out in https://github.com/marcosfad/mbp-ubuntu-kernel/blob/master/patch_driver.sh#L36
The drivers were not able to be loaded.
I would be thankful if you do a pull request after you get it to work.
You can check my other repo with the live ISO. https://github.com/marcosfad/mbp-ubuntu.
I wasn't able to build an iso, were the keyboard and the touch bar worked correctly.

**Comment by zappacor** [comment]
Ok, I see. Then it's a bit misleading... it's only one patch (`APPLE_SMC_DRIVER`) which gets included, am I right?
What about adding the files for `APPLE_BCE_DRIVER` and `APPLE_IB_DRIVER` from their repos as part of the `linux-image-*.deb` file such that they are copied into their corresponding `/usr/src/<module_name>-<version>` on package installation + forcing an initram update?
Not the same and as good as trully patching the kernel but better than the manual `dkms` installation.

**Comment by marcosfad** [comment]
What do you mean to add the files directly? Is that possible? *.deb are compiled files. I don't know how to do that. Maybe you can create a pull request with the changes required for that. I would be glad to stop using DKMS.

**Comment by zappacor** [comment]
What I was suggesting was to use `dkms` to build the modules and then add the `*.ko` module files it creates into the `linux-image.*.deb` packages you release.

That said, while exploring that possibility, I found an yet better way: take a look at the `mkbmdeb` command (from `man dkms`):
```
mkbmdeb [module/module-version] [-k kernel/arch]
  Creates a Debian binary package containing just the binary modules in the /lib/modules installation path. This
  package does not depend on dkms and does not require a toolchain to be installed on the target host. Useful
  if you want to have a package to install on hosts identical to the build system without installing the full
  toolchain on them. It uses a template debian  directory  found in /etc/dkms/template-dkms-mkbmdeb as the
  basis for the package.
```
I think that opens the possibility to build the MBP modules against an official (plain, non-patched) Ubuntu kernel package and then release just the `.deb` package `mkbmdeb` creates as, say, an "addition" to the official kernel.

What you think?

**Comment by zappacor** [comment]
Just as an update, I spent some time this weekend on it and could make them part of the kernel.
Will update, possibly by creating a pull request, as soon as I can. Not doing it just now simply 'cause I'm exhausted.  :-(
